version: '3.8'
services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - redis_path=redis
      - db_path=mysql+pymysql://root:adkb@mysql:3306/portfolio
  
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
  
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: adkb
      MYSQL_DATABASE: portfolio
    volumes:
      - type: bind 
        source: ./mydb
        target: /var/lib/mysql
  
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
  
    
