version: '3'

services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - 6000:5000
    volumes:
      - ./registry-volume:/var/lib/registry
      - ./certs:/certs
      - ./auth:/auth
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry_auth.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry_auth.key 
  registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry-fe
    ports:
      - 8080:80
    environment:
      ENV_DOCKER_REGISTRY: 127.0.0.1
      ENV_DOCKER_REGISTRY_PORT: 6000