apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: fastapi
    template:
        metadata:
            labels:
                app: fastapi
        spec:
            containers:
            - name: fastapi-container
              image: fastapi:local
              ports:
              - containerPort: 8000