name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-copy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: copy all components(backend,fronted)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "*"
        target: "/home/ubuntu/2024-portfolio/"

  deploy:
    runs-on: ubuntu-latest
    needs: ['build-and-copy']
    steps:
    - name: SSH and Run Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
            cd 2024-portfolio
            docker-compose up -d --build
            docker cp backend/scripts/nginx/default.conf nginx:/etc/nginx/conf.d
            docker exec -it nginx /usr/sbin/nginx -s reload